"""Default tool costs, priorities, and planning caps for AuditDecisionMaker."""

from __future__ import annotations


DEFAULT_TOOL_COSTS: dict[str, int] = {
    "passive_config_audit": 3,
    "service_banner_probe": 4,
    "tls_service_probe": 4,
    "dns_zone_audit": 4,
    "reverse_dns_probe": 2,
    "ssh_auth_audit": 5,
    "smtp_security_check": 5,
    "mysql_handshake_probe": 4,
    "postgres_handshake_probe": 4,
    "redis_exposure_check": 5,
    "memcached_exposure_check": 5,
    "git_exposure_check": 2,
    "source_map_detector": 2,
    "error_page_analyzer": 3,
    "waf_detector": 3,
    "security_txt_check": 1,
    "tech_stack_fingerprint": 2,
    "js_endpoint_extractor": 4,
    "login_form_detector": 3,
    "http_security_headers": 3,
    "ssl_expiry_check": 3,
    "subdomain_enum_passive": 5,
    "cors_misconfiguration": 5,
    "dynamic_crawl": 12,
    "active_web_crawler": 12,
    "api_schema_discovery": 4,
    "page_vision_analyzer": 7,
    "sql_sanitization_audit": 8,
    "xss_protection_audit": 8,
    "param_fuzzer": 6,
    "cookie_security_audit": 3,
    "csp_evaluator": 4,
    "nmap_scan": 15,
    "dirsearch_scan": 10,
    "nuclei_exploit_check": 20,
    "cve_lookup": 5,
    "cve_verify": 25,
    "rag_intel_lookup": 3,
    "poc_sandbox_exec": 18,
}

DEFAULT_TOOL_PRIORITIES: dict[str, int] = {
    "passive_config_audit": 0,
    "git_exposure_check": 2,
    "security_txt_check": 3,
    "dns_zone_audit": 15,
    "reverse_dns_probe": 16,
    "tech_stack_fingerprint": 1,
    "login_form_detector": 4,
    "http_security_headers": 5,
    "ssl_expiry_check": 6,
    "source_map_detector": 7,
    "js_endpoint_extractor": 8,
    "subdomain_enum_passive": 9,
    "error_page_analyzer": 11,
    "waf_detector": 13,
    "nmap_scan": 14,
    "service_banner_probe": 15,
    "ssh_auth_audit": 16,
    "redis_exposure_check": 17,
    "memcached_exposure_check": 18,
    "smtp_security_check": 19,
    "mysql_handshake_probe": 20,
    "postgres_handshake_probe": 21,
    "tls_service_probe": 12,
    "api_schema_discovery": 18,
    "page_vision_analyzer": 19,
    "dynamic_crawl": 20,
    "active_web_crawler": 21,
    "cors_misconfiguration": 22,
    "csp_evaluator": 23,
    "cookie_security_audit": 24,
    "dirsearch_scan": 25,
    "sql_sanitization_audit": 30,
    "xss_protection_audit": 30,
    "param_fuzzer": 32,
    "cve_lookup": 35,
    "nuclei_exploit_check": 40,
    "cve_verify": 45,
    "rag_intel_lookup": 28,
    "poc_sandbox_exec": 42,
}

DEFAULT_AVAILABLE_TOOLS: tuple[str, ...] = tuple(DEFAULT_TOOL_PRIORITIES.keys())

DEFAULT_TOOL_SELECTION_CAPS: dict[str, dict[str, int]] = {
    "conservative": {
        "passive_config_audit": 1,
        "service_banner_probe": 1,
        "tls_service_probe": 1,
        "dns_zone_audit": 1,
        "reverse_dns_probe": 1,
        "ssh_auth_audit": 1,
        "smtp_security_check": 1,
        "mysql_handshake_probe": 1,
        "postgres_handshake_probe": 1,
        "redis_exposure_check": 1,
        "memcached_exposure_check": 1,
        "git_exposure_check": 1,
        "source_map_detector": 1,
        "error_page_analyzer": 1,
        "waf_detector": 1,
        "security_txt_check": 1,
        "tech_stack_fingerprint": 1,
        "login_form_detector": 1,
        "js_endpoint_extractor": 1,
        "http_security_headers": 1,
        "ssl_expiry_check": 1,
        "cors_misconfiguration": 1,
        "api_schema_discovery": 1,
        "page_vision_analyzer": 0,
        "sql_sanitization_audit": 1,
        "xss_protection_audit": 1,
        "param_fuzzer": 1,
        "cookie_security_audit": 1,
        "csp_evaluator": 1,
        "cve_lookup": 1,
        "cve_verify": 0,
        "rag_intel_lookup": 1,
        "poc_sandbox_exec": 0,
        "dynamic_crawl": 0,
        "active_web_crawler": 0,
        "dirsearch_scan": 0,
        "nuclei_exploit_check": 0,
        "nmap_scan": 1,
        "subdomain_enum_passive": 1,
    },
    "balanced": {
        "passive_config_audit": 1,
        "service_banner_probe": 2,
        "tls_service_probe": 1,
        "dns_zone_audit": 1,
        "reverse_dns_probe": 1,
        "ssh_auth_audit": 1,
        "smtp_security_check": 1,
        "mysql_handshake_probe": 1,
        "postgres_handshake_probe": 1,
        "redis_exposure_check": 1,
        "memcached_exposure_check": 1,
        "git_exposure_check": 1,
        "source_map_detector": 1,
        "error_page_analyzer": 1,
        "waf_detector": 1,
        "security_txt_check": 1,
        "tech_stack_fingerprint": 1,
        "login_form_detector": 1,
        "js_endpoint_extractor": 1,
        "http_security_headers": 1,
        "ssl_expiry_check": 1,
        "cors_misconfiguration": 1,
        "api_schema_discovery": 1,
        "page_vision_analyzer": 1,
        "sql_sanitization_audit": 2,
        "xss_protection_audit": 2,
        "param_fuzzer": 2,
        "cookie_security_audit": 1,
        "csp_evaluator": 1,
        "cve_lookup": 1,
        "cve_verify": 1,
        "rag_intel_lookup": 1,
        "poc_sandbox_exec": 0,
        "dynamic_crawl": 1,
        "active_web_crawler": 1,
        "dirsearch_scan": 1,
        "nuclei_exploit_check": 1,
        "nmap_scan": 1,
        "subdomain_enum_passive": 1,
    },
    "aggressive": {
        "passive_config_audit": 2,
        "service_banner_probe": 4,
        "tls_service_probe": 2,
        "dns_zone_audit": 1,
        "reverse_dns_probe": 2,
        "ssh_auth_audit": 2,
        "smtp_security_check": 2,
        "mysql_handshake_probe": 2,
        "postgres_handshake_probe": 2,
        "redis_exposure_check": 2,
        "memcached_exposure_check": 2,
        "git_exposure_check": 1,
        "source_map_detector": 1,
        "error_page_analyzer": 1,
        "waf_detector": 1,
        "security_txt_check": 1,
        "tech_stack_fingerprint": 2,
        "login_form_detector": 2,
        "js_endpoint_extractor": 2,
        "http_security_headers": 2,
        "ssl_expiry_check": 2,
        "cors_misconfiguration": 2,
        "api_schema_discovery": 1,
        "page_vision_analyzer": 1,
        "sql_sanitization_audit": 3,
        "xss_protection_audit": 3,
        "param_fuzzer": 3,
        "cookie_security_audit": 2,
        "csp_evaluator": 2,
        "cve_lookup": 2,
        "cve_verify": 2,
        "rag_intel_lookup": 2,
        "poc_sandbox_exec": 1,
        "dynamic_crawl": 1,
        "active_web_crawler": 1,
        "dirsearch_scan": 1,
        "nuclei_exploit_check": 1,
        "nmap_scan": 1,
        "subdomain_enum_passive": 1,
    },
}

PATH_CAPPED_TOOLS: dict[str, int] = {
    "sql_sanitization_audit": 3,
    "xss_protection_audit": 3,
}

STANDARD_PORT_PRIORITY: dict[tuple[str, int], int] = {
    ("https", 443): 0,
    ("http", 80): 1,
    ("https", 8443): 2,
    ("http", 8080): 3,
    ("http", 8000): 4,
    ("http", 8008): 5,
    ("http", 8888): 6,
    ("http", 3128): 7,
    ("http", 5800): 8,
}
